name: "Theme Update"

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write  # Pull Request 생성 및 저장소 변경 권한

jobs:
  update-theme:
    runs-on: ubuntu-latest
    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: main

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Hugo 설치
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: "latest"
          extended: true

      # 4. Hugo 모듈 업데이트
      - name: Update hugo modules
        run: |
          hugo mod get -u     # 모든 모듈의 최신 버전으로 업데이트
          hugo mod tidy       # 필요없는 종속성 정리 - clean up go.sum and go.mod

      # 5. Node.js 종속성 설치
      - name: Install node modules
        run: npm install

      # 6. 사이트 빌드
      - name: Build
        run: hugo --minify

      # 7. Pull Request 생성
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update Hugo modules and dependencies"
          title: "Update theme and dependencies"
          body: "This PR updates Hugo modules and npm dependencies."
          base: main
          branch: "update-theme"
          labels: automerge